# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-04"

[[extensions]]
name = "design-preview"
handle = "design-preview"
type = "ui_extension"
uid = "515519ed-b669-3dd0-83f4-1011c49ebbd5d0e380ea"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.cart-line-item.render-after"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.thank-you.cart-line-item.render-after"
