name = "brightfield-mockup-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = true

[[r2_buckets]]
binding = "MOCKUP_STAGING"
preview_bucket_name = "mockup-staging"
bucket_name = "mockup-staging"
